###############################################################################
#
#   Config file for this Snakemake pipeline.
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 22-11-2019
#   LICENSE: Apache_2.0
#
###############################################################################
---

# scripts directory for this pipeline
scripts_directory: "src"

# genomic annotation file in GTF format
gtf: "../../RESOURCES/Homo_sapiens.GRCh38.87.gtf"

# genomic sequence in FASTA format
genome: "../../RESOURCES/Homo_sapiens.GRCh38.dna.primary_assembly.fa"

# path to the directory with transcriptome index
# if the directory does not exist it will be created based upon the
# genome and gtf files above
transcriptome_index: "../../RESOURCES/Homo_sapiens.GRCh38_transcriptome_index"

# path for the output directory
output_dir: "sample_output_dir"

# path to the experiment design table in TSV format (specified in README)
design_table: "sample_design_table.tsv"

# sequencing type: 'single_end' vs 'paired_end'
seqtype: "paired_end"

# minimal gene expression cutoff for filtering in DRIMSeq
minimal_gene_expression: "10"

# minimal transcripts expression cutoff for filtering in DRIMSeq
minimal_transcript_expression: "10"

# minimal transcripts proportion for filtering in DRIMSeq
minimal_transcripts_proportion: "0.1"

# alpha parameter value for testing statistical significance
statistical_alpha: "0.05"

...
